### ISSUE TITLE
Code Check-in

### ISSUE THREAD

**Issue by jpotts244** [jpotts244/jpotts244.github.io#1]
Hi Anna, 

Wondering if I can talk through my project with you sometime today? It is pretty basic and it works, so I am OK with that- I would love to be able to show you it before the big day.  If you are busy it is totally cool, this is not an emergency. :-)

Let me know! Thank  you!

**Comment by annarankin** [comment]
Hey Jackie, no problem, that'd be good! Want to meet in about an hour?

**Comment by jpotts244** [comment]
Sure! thanks! Let me know where to meet you!
